<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MicronautExampleJdbcTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>12bd93ba-2af2-4073-bb7f-fc0ed250a5af</testSuiteGuid>
   <testCaseLink>
      <guid>ea9dcc21-d5bd-4cf4-b442-5311ab846f04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_FindPetsByName</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc52b7c6-2d4d-44db-a9ce-fc12859f1953</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c50630f-35f0-4ea2-8045-4351bab56e1c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
